### ISSUE TITLE
Choose color palette

### ISSUE THREAD

**Issue by asportnoy** [codeths/kitcoin#1]

**Comment by asportnoy** [comment]
Eli will figure out what colors to use
https://daisyui.com/core/colors
https://daisyui.com/docs/add-themes

**Comment by edcous** [comment]
Thing for dark mode toggle on chromebooks (from daisyui): https://github.com/saadeghi/theme-change

**Comment by asportnoy** [comment]
I put in some colors (including dark mode) and deployed it in [v0.1.3](https://github.com/chromezoneeths/kitcoin/releases/tag/v0.1.3). These colors aren't finalized.

**Comment by asportnoy** [comment]
Closing per @edcous's request.
