### ISSUE TITLE
Some email changes not honored

### ISSUE THREAD

**Issue by mswider** [codeths/kitcoin#110]
I've discovered an issue which impacts a very small set of users: people who've had their email changed in Google.
Our code actually works fine and correctly attempts to make the changes, but MongoDB gives a `duplicate key error`, meaning that one of our indexes (email) is set to be unique, but the email we're trying to change to already exists in the index. 
This might seem strange, and it is, but it's because whoever was responsible for moving the account over did something strange:
![image](https://github.com/codeths/kitcoin/assets/37093293/b78624a0-28db-490d-ad73-e6be90209d27)
Rather than just changing the user's email, the person responsible usually created a new account for the user, which we then synced at some point in time, but was later deleted. Interestingly, this new (and now deleted) account was never actually used by the actual user.
This is because some time later, the real account was moved over to the new email address, continuing as normal.   

What this ends up meaning is that we already have an account saved for the new email address by the time that the user's actual account gets moved over, which causes problems.
Another interesting thing here is that this annoying temporary account which gives us so much trouble does not show up in Google Admin queries at all anymore, almost like it just disappeared. Because Google never tells us that the account was archived or suspended, we don't remove it.  

We end up with a series of unfortunate events here. The obvious solution would be to make the email index _not_ unique, which would let us sync these users successfully. 
That would work, but we would still have these temporary accounts that have never been used and will never be used by anyone. The fact that name and email changes are involved here makes it more important that these accounts are gone, because you probably wouldn't want an old name showing up anymore if you've gone through the trouble of changing it.

**Comment by mswider** [comment]
## Todo:
- [x] Make `email` index not unique
- [x] Remove problem accounts

**Comment by mswider** [comment]
@edcous
How do you think we should identify these problematic accounts?
Thoughts?

**Comment by edcous** [comment]
I thought we deleted Kitcoin data when the account no longer exists in Google admin?

**Comment by mswider** [comment]
> I thought we deleted Kitcoin data when the account no longer exists in Google admin?

https://github.com/codeths/kitcoin/blob/e929c4df5e590dd008dcaecf4b4b8971e74c762d/src/helpers/admin.ts#L75
So we only remove accounts if they're in an ignored OU or marked as suspended or archived by Google.
Since Google doesn't even return these deleted accounts for some reason, we don't loop over them in the admin sync.

**Comment by edcous** [comment]
Maybe the solution is to flag when an account is in the kitcoin database but not in admin?

**Comment by mswider** [comment]
I've gotten accounts to sync properly at this point, now on to removing the temporary users

**Comment by mswider** [comment]
Waiting on https://github.com/codeths/kitcoin/issues/111
