### ISSUE TITLE
Clean up dummy text and placehoders

### ISSUE THREAD

**Issue by asportnoy** [codeths/kitcoin#5]

**Comment by asportnoy** [comment]
@WZMorton I started this. We still need text for the metatags (located in index.html) and the home page.

**Comment by mswider** [comment]
What if the description was something like 
> Earn Kitcoin from your teachers, spend it on ETHS stuff or in custom stores

(this isn't that good but something like it)

**Comment by asportnoy** [comment]
That general idea is good. Basically saying what KitCoin is. But we definitely want to reword it.

**Comment by WZMorton** [comment]
I think this could be good for the metatags
> Kitcoin is a digital currency that ETHS students can earn from teachers or staff, and spend on items within various school stores.

What do you guys think?

**Comment by asportnoy** [comment]
Minor tweaks

> Kitcoin is a digital currency that ETHS students can earn from teachers or staff and spend in school stores.

**Comment by asportnoy** [comment]
We also need a description for the homepage
<img width="1440" alt="Screenshot on 2022-01-07 at 13 42 42" src="https://user-images.githubusercontent.com/14863373/148598282-6cf3da4e-e9e7-42f2-a6fb-3014744ca2ad.png">

**Comment by WZMorton** [comment]
Everything should be good now.

**Comment by asportnoy** [comment]
> Everything should be good now.

I’m not seeing any new commits. Did you push them?

**Comment by asportnoy** [comment]
Nevermind, I see it. For next time, please update the submodule as well.
