### ISSUE TITLE
Reports/Statistics for admin page

### ISSUE THREAD

**Issue by asportnoy** [codeths/kitcoin#58]

**Comment by mswider** [comment]
Should this be done by querying the db or updating statistics when events occur?

**Comment by asportnoy** [comment]
I think querying would be better. We can have a button on the admin page to run them.

We still need to decide what information to include and how to format it. I was thinking a CSV would be good.

**Comment by mswider** [comment]
> I think querying would be better. We can have a button on the admin page to run them.
> 
> We still need to decide what information to include and how to format it. I was thinking a CSV would be good.

That's what I was thinking, we just need to make sure to not have commas in the data stored which might be weird if we're storing balances above 999 or stuff like that which would have commas.

**Comment by asportnoy** [comment]
> we just need to make sure to not have commas in the data stored which might be weird if we're storing balances above 999 or stuff like that which would have commas.

The balance is stored as a number and is formatted in the frontend, so that shouldn't be an issue.

We can use [json-2-csv](https://www.npmjs.com/package/json-2-csv) to create the CSVs. The library can also be used in reverse which we can use for #36.

**Comment by asportnoy** [comment]
- Kitcoin sent per day
- Transactions per day
- Amount in circulation (total balances of students)
- Highest staff kitcoin sent
- Highest student balance
- Highest student purchasing

**Comment by asportnoy** [comment]
Progress for this issue is tracked in #81.
