### ISSUE TITLE
Bug with version check

### ISSUE THREAD

**Issue by asportnoy** [codeths/kitcoin#89]
The version check API introduced in #88 will not work in development as that still uses the old command to start.
https://github.com/codeths/kitcoin/blob/83c6005162bc880fcb345c6aac0ee2a7fa937a45/gulpfile.js#L256

**Comment by mswider** [comment]
Are you able to reproduce this?
I tested that when I made the change and it worked (might be because the process it spawns inherits the env variables that it got when it was run with npm run dev)

**Comment by asportnoy** [comment]
Good point. But you might as well just switch it for consistency. Would also make it easier if the start command changes in the future.

**Comment by asportnoy** [comment]
Also if you update the package json while a dev session is running then right now it won't update until you restart the dev session.

**Comment by mswider** [comment]
I was considering switching it but I noticed that the gulp command tries to kill the process with SIGINT
This works if we just use `node .` but `npm start` doesn't seem to respond to SIGINT, so the process keeps running in the background which causes issues

I do agree that switching it would be an improvement though, but the gulp command would need changes

**Comment by mswider** [comment]
> Also if you update the package json while a dev session is running then right now it won't update until you restart the dev session.

This is probably fine
If we wanted to make this work we would have to change how we get the version and it would have to be loaded every time the endpoint gets a request

I think it's easy enough to just restart the dev session if this is an issue
